In [226]:
#load train_data,train_label
import numpy as np
train = np.genfromtxt("train.csv", encoding='UTF-8', delimiter=",")
train_data = np.array(train[1:,1:-2].astype(np.float))
train_label = train[1:,6].astype(np.float)
print('num of train_data:%d'%train_data.shape[0])
print('num of feature:%d'%train_data.shape[1])
print('num of labels:%d'%train_label[-1])

num of train_data:123
num of feature:4
num of labels:4


In [227]:
#load test_data
test =np.genfromtxt("test.csv", encoding='UTF-8', delimiter=",")
test_data = np.array(test[1:,1:].astype(np.float))
print('num of test_data:%d'%train_data.shape[0])

num of test_data:123


In [228]:
#check nan value
train_data[np.isnan(train_data)]=0
test_data[np.isnan(test_data)]=0

In [232]:
#build svc model
from sklearn.svm import SVC
model=SVC()
model.fit(train_data, train_label)
print('accuracy :%.2f'%model.score(train_data, train_label))

accuracy :0.98


In [233]:
#confusion_matrix of training
from sklearn import metrics
print('training_confusion_matrix')
print(metrics.confusion_matrix(train_label, model.predict(train_data)))

training_confusion_matrix
[[40  0  0  0]
 [ 0 38  2  0]
 [ 0  0 40  0]
 [ 0  0  1  2]]


In [235]:
# precision recall f1-score
print((metrics.classification_report(train_label,model.predict(train_data))))

             precision    recall  f1-score   support

        1.0       1.00      1.00      1.00        40
        2.0       1.00      0.95      0.97        40
        3.0       0.93      1.00      0.96        40
        4.0       1.00      0.67      0.80         3

avg / total       0.98      0.98      0.98       123



In [236]:
#predict test_data
prediction = model.predict(test_data)
print(prediction)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3.
 3. 3. 2. 3. 3. 3.]


In [237]:
#save to csv file
result=[]
index=[]
for i in range(len(prediction)):
    index.append(i+1)
    result.append(prediction[i])
index=np.array(index)
result=np.array(result)
print(index)
print(result)
np.savetxt('result.csv', np.column_stack((index,result)), fmt='%d', delimiter = ',',header=('id,type'),comments='')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3.
 3. 3. 2. 3. 3. 3.]


In [238]:
#kagle accuracy =1
solution = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3])
print(metrics.confusion_matrix(solution, prediction))

[[10  0  0]
 [ 0 11  0]
 [ 0  0  9]]
